name: "Create Tagged Release"

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version number of the release'
        required: true

jobs:
  gh_tagged_release:
    name: Create tagged release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Update version in manifest.json
        run: |
          cd ${{ github.workspace }}/custom_components/radar_warnings
          jq '.version = "${{ github.event.inputs.release_version }}"' manifest.json > temp.json
          mv temp.json manifest.json

      - name: Build
        run: |
          cd ${{ github.workspace }}/custom_components/radar_warnings
          zip radar_warnings.zip -r ./

      - name: "Create Github release (full)"
        if: ${{ !contains( github.event.inputs.release_version, '-rc' ) }}
        uses: softprops/action-gh-release@v2
        id: radar_warnings_release
        with:
          body: "Release version ${{ github.event.inputs.release_version }}."
          tag_name: ${{ github.event.inputs.release_version }}
          target_commitish: "main"
          draft: false
          prerelease: false
          files: ${{ github.workspace }}/custom_components/radar_warnings/radar_warnings.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

      - name: "Notify issues of release their fix is contained in"
        uses: apexskier/github-release-commenter@3bd413ad5e1d603bfe2282f9f06f2bdcec079327 # v1.3.6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template: |
            Release {release_link} addresses this.


